### ISSUE TITLE
[Bug]: Problème lié au log dans docker

### ISSUE THREAD

**Issue by AlexiFon** [IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04#42]
### What happened?

Fatal Error au lancement du docker pour LoggerInterface.php

### Version

0.2

### Relevant log output

Fatal error: Uncaught Error: Interface "Psr\Log\LoggerInterface" not found in /app/vendor/monolog/monolog/src/Monolog/Logger.php:35
Stack trace:
#0 /app/vendor/composer/ClassLoader.php(576): include()
#1 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#2 /app/connexionMQTT.php(11): Composer\Autoload\ClassLoader->loadClass('Monolog\\Logger')
#3 {main}
  thrown in /app/vendor/monolog/monolog/src/Monolog/Logger.php on line 35

**Comment by AlexiFon** [comment]
Correction du bug en changeant le composer.json et ajout de la ligne commande pour le lancement du script php.

**Comment by AymenCharouki** [comment]
Fixé sur ma machine, problème lié au git ignore.
